### ISSUE TITLE
[Idea] Single Slot Interface

### ISSUE THREAD

**Issue by TheSnowyChickens** [phantamanta44/Lazy-AE2#1]
Hello,
the AE Interface has a size for 9 patterns, but some modded machines don't need 9 spaces for patterns, they only need 1. (as example the auto crafting from charged certus via charger or every other machine with only 1 usage)

So now the question, if you could create a cheaper interface with only 1 slot ? ;)

**Comment by phantamanta44** [comment]
I feel that this is out of scope; the point of Lazy AE2 is to simplify certain processes, and making a cheaper interface does not constitute simplification
