### ISSUE TITLE
Redstone and silicon gets inserted in middle slot in Circuit Etcher

### ISSUE THREAD

**Issue by pabluuz** [phantamanta44/Lazy-AE2#10]
steps to reproduce:
Get chest full of redstone and/or silicon and pipe it with enderIO conduits to top slot of etcher. Etcher shouldn't accept both of those in middle slot. 

possible solution ideas: 
-lockdown of slots, to only accept locked item
-leave 1 item to reserve space
-disable redstone and silicon in middle slots (like they're blocked in top spot in AE inscriber)

![image](https://user-images.githubusercontent.com/10631173/71447877-a21fd800-2734-11ea-9099-0922d3a15cb1.png)

**Comment by phantamanta44** [comment]
oh, whoops. should be a quick fix
