### ISSUE TITLE
Mass Assembler Controller drop？

### ISSUE THREAD

**Issue by EnterFor** [phantamanta44/Lazy-AE2#17]
First thanks to the author for making this excellent module, I love it!!
I have a problem now
After testing, the Mass Assembler Controller will become a drop after the server restarts
Players with this problem have ME Security Terminal. Can you fix this error?
My English is not good. I am Chinese

**Comment by EnterFor** [comment]
pictures：https://i.loli.net/2020/02/06/XFh84r6WfQcyClP.jpg

**Comment by phantamanta44** [comment]
oh oops, i forgot to write security data to them. currently in class but i'll try to get a fix out asap

**Comment by EnterFor** [comment]
> 哦，糟糕，我忘了向他们写入安全数据。目前在上课，但我会尽快解决

i love you !!THX!
