### ISSUE TITLE
[Suggestion] Max size limits for Mass Assembler

### ISSUE THREAD

**Issue by idnthvn** [phantamanta44/Lazy-AE2#19]
During Testing:
I made an AE2 system and did some testing on how large a Mass Assembler can go. 
I first created a 32x32x32 with success with the Controller, however during the creation, it caused massive lag spike in the server. After that, i tried to access the gui and it kicks me or the player off the server and creates another large lag spike.
I also tested this with 30x30x30.

Next, I created a 16x16x16 system that works with little to no lag and the gui is accessible.

Please limit this to say a 16x16x16 structure (which is PLENTY big enough to hold a lot). Where as the controller will not allow such a structure bigger than 16x16x16. This will allow servers to not get spammed with large assemblers that lag the server and that players don't get kicked. 

Forge Version 1.12.2 2847
SpongeForge Version 7.1.9 RC3989
Hope that helps :)

**Comment by EnterFor** [comment]
Support you, I also want this configurable feature
