### ISSUE TITLE
[Idea] Wireless Channel Controller/Block

### ISSUE THREAD

**Issue by TheSnowyChickens** [phantamanta44/Lazy-AE2#2]
Hi again,

I have an idea for a block / function, that fits with your mod name^^
-> Wireless Channel Controller/Block

The block is easy explained:
- up to 8 channel  support
- wireless connection with machines
- 1 big GUI to change the interaction with the machines
- linking tools to connect the machines

Picture explained:
- 1: Linking Tool Slot for every connected machine (1 linking tool for 1 machine)
- 2: Check box for the display (4.), it contains some info about the machine
- 3: AE2 blocks (like the interface, import/export bus, storage bus and more) which are connected to this specific machine. (more settings in point 6.)
- 4: Display :^)
- 5: Linking Tool reset field + button (it clears nbt tags, metadata and more)
- 6: Setting buttons: these buttons open the interface from the specific item, that is connected to 1 machine. Just press the check box and then the settings button to open, as example, the interface of the export bus. (there you can adjust all the values and add/clear cards, whitelist options...)

![grafik](https://user-images.githubusercontent.com/29357962/58488904-83d80680-816a-11e9-8f44-8b5bcba847a6.png)

Advantages:
- The player need less cables to connect all the machines

Okay, puhhh, I hope my idea is understandable. Maybe I explained it some monotonous, because my english is not the best. :=)

Please let me know if it is even possible. xD

**Comment by phantamanta44** [comment]
I feel that this is out of scope; the cabling system is simple enough as it stands
