### ISSUE TITLE
ME Interface Terminal can't fand the Mass Assembly Chamber

### ISSUE THREAD

**Issue by magcicada** [phantamanta44/Lazy-AE2#20]
I connected the Mass Assembly Chamber to the ME Controller. The Mass Assembly Chamber works well, but the Mass Assembly Chamber cannot be found in the ME Interface Terminal.
![2020-02-17_09 41 24](https://user-images.githubusercontent.com/45464670/74617749-b3e88f00-5169-11ea-8b15-60095af34e47.png)
![2020-02-17_09 45 00](https://user-images.githubusercontent.com/45464670/74617844-3a04d580-516a-11ea-8e19-5188838b71b8.png)
![2020-02-17_09 45 08](https://user-images.githubusercontent.com/45464670/74617848-3ffab680-516a-11ea-941f-df485aac14cc.png)

**Comment by phantamanta44** [comment]
sorry, but that's just how it is; the interface terminal is hard-coded to only interact with ME interfaces

**Comment by Manuepolis23** [comment]
can it be a solution to create a new terminal that will combine both?

**Comment by phantamanta44** [comment]
i don't think that's a great idea. imagine if every mod that added external processing providers added their own interface terminals -- that would be pretty terrible

**Comment by idnthvn** [comment]
What if you created a seperate "terminal" a Mass Assembler Interface Terminal?

**Comment by idnthvn** [comment]
> can it be a solution to create a new terminal that will combine both?
Would a solution be a seperate terminal? A Mass Assembler Interface Terminal that would open the gui from the other location, rather than at the assembler itself. Not a combined interface. Just one dedicated for the mass assembler.

**Comment by phantamanta44** [comment]
i strongly suggest just placing a travel anchor or similar near your mass assembler so you can blink over to it whenever you need to add new patterns

**Comment by magcicada** [comment]
I opened a PR and uploaded the zh_cn.lang file, check it please, thank you.

**Comment by balthild** [comment]
> i strongly suggest just placing a travel anchor or similar near your mass assembler so you can blink over to it whenever you need to add new patterns

Teleporting between the chamber and terminals isn't convenient enough when encoding recipes for items that require lots of steps to craft, for example, those items in GregTech. Also, many players prefer a kind of network building styles that have a "central control room". Adding a terminal does not affect players like teleporting frequently, but could satisfy those prefer operating everything of the network at one place -- so, why not?

**Comment by phantamanta44** [comment]
i added an i/o port for the MA chamber in the latest update. you can slap a storage bus on the i/o port then route a terminal to your control room (e.g. via p2p) to simulate an interface terminal

**Comment by hbro** [comment]
Ran into this minor inconvenience just now, and I was actually looking for an I/O port block in JEI. Thumbs up for a perfect solution!

**Comment by magcicada** [comment]
I thought this topic was dead,thank you for still looking for new ways to solve it.It is very inconvenient when I play in GregTech.
