### ISSUE TITLE
ME level maintainer causes server lag

### ISSUE THREAD

**Issue by EnterFor** [phantamanta44/Lazy-AE2#23]
With a lag, I used TickProfiler to calculate the results as follows
https://i.loli.net/2020/03/01/LDiryoJXsCMhR4x.png

When I teleported over and took out the contents, the lag disappeared.
This is what was in there at the time：https://i.loli.net/2020/03/01/4AW7cVi5BxlH6Xp.png

I don't know if you can understand me. My English is terrible

**Comment by idnthvn** [comment]
laggoggles also sees this as a high usage machine

**Comment by EnterFor** [comment]
No, I'm not using the laggoggles
i used TickProfiler

**Comment by idnthvn** [comment]
I was saying when i did Laggoggles on my SpongeForge server as well, That it picks each one up for large usage.

**Comment by EnterFor** [comment]
Sorry, I didn't understand it before. My English is not good
But the author seems to have disappeared

**Comment by phantamanta44** [comment]
i'm watching this ticket but i'm currently very busy with schoolwork and can't investigate the issue

**Comment by phantamanta44** [comment]
okay so from a little investigation, it seems like the lag is an inherent part of ae2's autocrafting system, and the way ae2 itself deals with it is by only submitting autocrafting jobs once every few seconds. the level maintainer, however, was trying to submit a job every tick, which is apparently very expensive. i think the solution is to just delay a couple seconds between every attempt to submit a job and for players to just increase batch size if they want to increase the refill rate.

**Comment by phantamanta44** [comment]
try out [this release](https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/2905120) and see if the lag is reduced somewhat

**Comment by phantamanta44** [comment]
i'd like to know if the fix worked before i close this issue. thanks

**Comment by idnthvn** [comment]
I havent noticed it. seems to be better. The only thing i see now is that the controller has high lag when player is not around but chunk is loaded. than i TP to it and it goes back to normal.
Or when the assembler has a massive recipe flowing through it. but i had other issues atm to determine if it was lazy ae2 or if it was something else
