### ISSUE TITLE
Mass Assembler disconnects from system

### ISSUE THREAD

**Issue by idnthvn** [phantamanta44/Lazy-AE2#24]
Lazy AE2 version 12
Sponge 7.1.10
Forge 1.12.2 version 2847

I have it tested with EnderIO conduits and each server reboot, the mass assembler disconnects.
I have not tested on regular AE2 cables yet but will do that now.
Also did this in version 9 of Lazy AE2

**Comment by idnthvn** [comment]
Tested, This does not happen with AE2 cables. Only EnderIO conduits

**Comment by phantamanta44** [comment]
by "disconnects", do you mean it drops as an item like in #25?

**Comment by phantamanta44** [comment]
ah, the ME conduit disconnects. i'll look into it
