### ISSUE TITLE
how 2

### ISSUE THREAD

**Issue by MrTrilB** [phantamanta44/Lazy-AE2#26]
Hi, I'm sorry about this but would you be able to write some instructions on how to put the mega structure together please

**Comment by Sonic2423** [comment]
https://www.curseforge.com/minecraft/mc-mods/lazy-ae2?comment=24

**Comment by phantamanta44** [comment]
^

i'll leave this issue open for the time being so i'll remember to write my dang wiki pages later

**Comment by phantamanta44** [comment]
ok https://github.com/phantamanta44/Lazy-AE2/wiki
