### ISSUE TITLE
Max job Queue

### ISSUE THREAD

**Issue by Miner28** [phantamanta44/Lazy-AE2#28]
Is it possible to increase Max Job Queue ? I couldn't find any config file or anything

Except hardcoded value here: https://github.com/phantamanta44/Lazy-AE2/blob/1.12.2/src/main/java/io/github/phantamanta44/threng/tile/TileBigAssemblerCore.java

Would be great if it would be possible.

**Comment by phantamanta44** [comment]
not at the moment. i'll work on adding a config option

**Comment by Miner28** [comment]
Awesome! Would be really good :) Or another idea: You could add a block that would increase Max job queue.. For example 4 per 1 block and real maximum would be set in config. This would be really good i think.

**Comment by Miner28** [comment]
I really love your mod and something like that would be great i think.

**Comment by phantamanta44** [comment]
here ya go: https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/2964330
