### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by heyheyhey123243** [phantamanta44/Lazy-AE2#29]
Just some suggestions for the mod.

- Page numbers added to the MAC
- The ability to search patterns in the MAC
- Previous page button to go back to the last page
- Not sure if this feature would be possible but the Preemptive Assembly Unit, maybe the ability to add facades to it like the base ME interface?

**Comment by phantamanta44** [comment]
i don't think facade support is worth it; it would be very very annoying to implement for a relatively small benefit. i'll get to work on the mass assembly chamber improvements, though
