### ISSUE TITLE
[idea] Refined storage´s addon: requestify but for AE

### ISSUE THREAD

**Issue by mariodk** [phantamanta44/Lazy-AE2#3]
https://minecraft.curseforge.com/projects/rs-requestify But for AE2 basically
but maybe 2-3 tiers of it:
the low tier: only 1 item to request your ME system to craft and have at all times
the mid tier: 4-5 items to request instead of 1 
the end tier: up to 9 

if just 1 tier machine then prefer not use up channels unless that 1 machine can request up to 9 items then its fine it use up channels

the current method of doing this with AE2 is kinda stupid & lame and not lazy at all to setup
and i think it use up like 2 channels for just request 1 item

**Comment by phantamanta44** [comment]
implemented in 944a03b
