### ISSUE TITLE
MA Chamber causes Pattern Terminal Lag

### ISSUE THREAD

**Issue by Hurricaneforces** [phantamanta44/Lazy-AE2#31]
When display more than 9 item in crafting of Pattern Terminal cause huge lag and fps drop . Remove item in crafting grid or disconnect MA Chamer then Terminal back to normal
Ver: 1.1.18

**Comment by phantamanta44** [comment]
sorry, but i'n not exactly sure what you mean. could you give a step-by-step walkthrough that replicates this issue from scratch?

**Comment by Hurricaneforces** [comment]
Step to produce:
1. Construct 11x11 MA Chamber and contain few pages of encoded pattern (my set up have 18 page of pattern)
2. Open ME Pattern Terminal and turn on processing pattern then place more than 6 crafting ingredient in crafting grid. After that lag will happen( more than 6 crafting ingredient in crafting grid is horrible lag, can’t take/put items  in ME Pattern Terminal)

**Comment by phantamanta44** [comment]
is it possible for you to perform profiling with e.g. visualvm? i'm having trouble replicating the issue and some more data might help isolate the problem faster
