### ISSUE TITLE
Request for further CraftTweaker documentation

### ISSUE THREAD

**Issue by smudgerox** [phantamanta44/Lazy-AE2#32]
I'm attempting to work on some recipe replacements so it doesn't break progression in a particular mod pack, however to me the documentation on the Curse Forge page isn't quite clear. Would you consider clarifying it a bit, or even possibly add it to the CT documentation repo?

https://github.com/CraftTweaker/CraftTweaker-Documentation

**Comment by Based199** [comment]
https://github.com/phantamanta44/Lazy-AE2/blob/1.12.2/README.md
scroll all the way down

**Comment by phantamanta44** [comment]
added a wiki page for crafttweaker
