### ISSUE TITLE
[request] more explanation in the wiki/docs

### ISSUE THREAD

**Issue by rlnt** [phantamanta44/Lazy-AE2#34]
Hello there,
I love Lazy AE2. I fell in love with it when using it in All The Mods 3 Expert which I am a dev for.

I would like to request a bit more explanation on the wiki for all the different mechanics of the mod.
Let's take the Mass Assembly Chamber for example.
It's explained how it's built and what it can do but not how it operates. I would like to know how exactly the MA Crafting Coprocessors affect the crafting process.
Another information that it needs is whether recipes are kept inside the block if you break it in case you want to add another MA Pattern Provider. And when does it lose it's recipes? If you break the controller?
Information about the pattern terminal would also be useful. Like that it's not accessible from it (btw is that intended or something you will implement in the future?).

Just have a bit more detailed wiki in general. I really like the mod and appreciate all your work.
I am glad that there is a wiki at least, not like many other mods do it. Keep it up!

**Comment by phantamanta44** [comment]
the thing is that I wrote the mod, so I don't really know which parts are going to be confusing. my idea was sort of that if people were confused about some particular subject, they could just ask in Discord, which would tell me that I need to update the wiki article on that subject. if you could give a more comprehensive list of stuff that you'd like to see clarified in the wiki, that would be helpful. for the time being, i'll update the MA article to be more specific about the internal mechanics

**Comment by rlnt** [comment]
Well, I have not seen it from that point yet but I fully get you there.
I will drop a list on the Discord asap when I find the time. Thanks for the quick response bud! :)
