### ISSUE TITLE
CraftTweaker problem

### ISSUE THREAD

**Issue by HaibaraGT** [phantamanta44/Lazy-AE2#35]
Hello author, I am using CT to modify the recipes, and I see the following code:
`addRecipe(ItemStack output, ItemMatcher input, [ItemMatcher topInput, ItemMatcher bottomInput]);

But I didn't find the description of ItemMatcher this type in the CraftTweaker document. 

I followed the ItemStack method to input, Crt prompts the following error message. Please provide some help, thank you.

error code：
[INITIALIZATION][CLIENT][ERROR] AE2.zs:10 > a method available but none matches the parameters (ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.item.IItemStack)
This is usually an error in your script, not in the mod
addRecipe(ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.item.IIngredient)

**Comment by phantamanta44** [comment]
make sure you're on the latest version of lazy ae2

**Comment by HaibaraGT** [comment]
> make sure you're on the latest version of lazy ae2

I used the latest version and the problem has been resolved. Thanks for your answer
Thank you！！
