### ISSUE TITLE
craftweaker issue with etcher

### ISSUE THREAD

**Issue by MoJoCreatior** [phantamanta44/Lazy-AE2#36]
using the wiki documentation for custom recipes using crafttweaker/modtweaker i wrote a small script to edit recipes.
```

mods.threng.Aggregator.addRecipe(<appliedenergistics2:material:22>,
<appliedenergistics2:material:18>,<ore:oc:circuitChip3>,<ore:circuitUltimate>);

mods.threng.Etcher.addRecipe(<appliedenergistics2:material:23>,
<appliedenergistics2:material:16>,<ore:oc:circuitChip3>,<ore:circuitUltimate>);
```

top one works fine,
but when trying to get etcher recipe to work it fails, ct syntax tells me that a method was found but it doesn't match the input parameters or something like that.

i skimmed through the crafttweaker integration classes and the only thing i saw that seemed off is that there is a return in the middle of a function. it seems like an odd place for it and only the etcher file has the return so i am thinking maybe that's the issue.

i was gonna try building a modified version simply with that line fixed but i couldn't get gradle to build it for me...... 
ran setupworkspace, i have jdk installed and in my system path, the library files are in the right place (as far as i can tell) just refuses to build. i can post some of the log output lines that state the cause,

https://github.com/phantamanta44/Lazy-AE2/blob/90f8a15f33aa8d2158515af8a091a2ffd56eeb1b/src/main/java/io/github/phantamanta44/threng/integration/crafttweaker/CrTClassEtcher.java#L24

-----------------------------------------------------

if this is not the cause of the issue, then idk,
in my scripts I'm simply going to use the aggregator to fulfill etcher recipes

**Comment by phantamanta44** [comment]
it sounds like you might be playing with an outdated version of lazyae2 that doesn't support 3-input etcher recipes

**Comment by MoJoCreatior** [comment]
I'll check that out RN,
i had to do a computer reset about a week ago and had to use old backups, (not THAT old, but definitely not super recent)
I'll update if it fixes problem...

**Comment by MoJoCreatior** [comment]
you're right, i was using an outdated version,
issue seems fixed so I'll close it

old version i had
1.1.16

new version as of post
1.1.20
