### ISSUE TITLE
Mass Assembly Controller causing huge lag when a Storage Bus is on its IO Port

### ISSUE THREAD

**Issue by aaronhowser1** [phantamanta44/Lazy-AE2#37]
![](https://cdn.discordapp.com/attachments/730325204550811708/756430644455669790/ca397431c9943d3a13039759bf84fea2.png)
![image](https://user-images.githubusercontent.com/15698722/93575329-1fdce100-f95f-11ea-8493-c350e701e30f.png)
![image](https://user-images.githubusercontent.com/15698722/93575431-400ca000-f95f-11ea-9ab2-ec2d6c22e6d1.png)

Using `lazy-ae2-1.12.2-1.1.21`, `libnine-1.12.2-1.1.9`, and `appliedenergistics2-rv6-stable-7`

**Comment by phantamanta44** [comment]
in theory, should be fixed upstream in libnine by https://github.com/phantamanta44/libnine/commit/0a22b728a5bdfadc206e04383f30a72121764c98. i'll leave this issue open for now because i'm not certain

**Comment by phantamanta44** [comment]
assuming that this is no longer an issue
