### ISSUE TITLE
Fluix Aggregator output problem.

### ISSUE THREAD

**Issue by abdullamu** [phantamanta44/Lazy-AE2#41]
hello
i just installed the mod to MC eternal and when i finally crafted the Fluix Aggregator and tried to automated it, it failed to push the output to the ME interface, so i tried to use the item conduit from Ender IO and again it failed to extract the items in the output slot, i did configure the IO to output as well as all, no luck.
Thanks for the great addon.

**Comment by abdullamu** [comment]
after restarting the game it seems to work fine.

**Comment by abdullamu** [comment]
well every time i place machine / every machine in this mod behave this way with the extraction problem/  i have to restart the world to make the extraction behave so i believe its bug.

**Comment by phantamanta44** [comment]
can i get a list of mods? i've never seen such behaviour before

**Comment by phantamanta44** [comment]
also, some screenshots of your setup could be helpful as well

**Comment by abdullamu** [comment]
Currently I'm not at home. The mods you can check if you see MC eternal modpack. And apparently it's happening with ender io item conduits, i used thermal expansion item ducts it seems to work fine. Im tring to automate the machines from lazy ae2 by mc interface and i used ender io as extraction methods since your machines doesnt push the output automatically. Maybe making machines pushing the output would ve great addition too.

**Comment by phantamanta44** [comment]
is the problem that the item conduits do not connect to the machine?

**Comment by abdullamu** [comment]
It does connect, but it doesn't extract the items stay in output slot.

**Comment by phantamanta44** [comment]
if you don't mind, could you send over a game log while the issue is occuring whenever you next get the opportunity?

**Comment by abdullamu** [comment]
I'll try to make video as well if possible. But would it be difficult to make button for machines to auto output outputs? It's would be easier than using another machine or item to extract outputs.

**Comment by phantamanta44** [comment]
it wouldn't be horribly difficult, i suppose. i'll consider it
