### ISSUE TITLE
[Performance] Level Maintainer cause notable load

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/Lazy-AE2#42]
I have 6 level mainteiners, mostly filled with levels: 
<img src="https://i.imgur.com/CRSV2Jy.png" width=300/> <img src="https://i.imgur.com/3j5Uxfv.png" width=300/>

They causing **continuous CPU load** (about 3% of tick time), even if idle (no new crafting tasks adding). It can be seeing through [Lag Goggles mod](https://www.curseforge.com/minecraft/mc-mods/laggoggles) and [Sampler](https://www.curseforge.com/minecraft/mc-mods/sampler).
There is screenshot of Sampler's snapshot:
<img src="https://i.imgur.com/Am35HhN.png" width=300/>

Is it expected load for this device?
How I can reduce CPU load by using Level Maintainer?

**Comment by phantamanta44** [comment]
it shouldn't be doing that unless there's actually something out of stock. that being said, there should probably be more aggressive backoff when a crafting job fails.

**Comment by Krutoy242** [comment]
Would be cool! I wish network parts that actually do nothing do not consume CPU.
