### ISSUE TITLE
Dupe not close interface

### ISSUE THREAD

**Issue by TheMartinfer22** [phantamanta44/Lazy-AE2#43]
Hello, I discovered a duplication bug, when you place an item inside a Lazy machine and a friend breaks the item it will be duplicated on the floor and it will stay on the machine!

https://prnt.sc/vk3ntl

Server build: Mohist lasted
Mod Version: 1.1.23
Minecraft Version: 1.12.2

**Comment by phantamanta44** [comment]
well, that's bad. i'll see if i can work out a quick hotfix
