### ISSUE TITLE
1.16 Support

### ISSUE THREAD

**Issue by miguelmoraesp** [phantamanta44/Lazy-AE2#47]
please.

**Comment by phantamanta44** [comment]
i write mods for the minecraft version i play, and i'm still playing on 1.12. you're free to port this yourself, if you want

**Comment by Spacelord09** [comment]
Any updates to this?

**Comment by phantamanta44** [comment]
see https://www.curseforge.com/minecraft/mc-mods/lazierae2

**Comment by Spacelord09** [comment]
Thanks for the link! Is that your project there?
If it is, is it planned to implement the following blocks in the new version as well?

- Mass Assembly Chamber
- ME Level Maintainer
- Preemptive Assembly Unit

**Comment by phantamanta44** [comment]
it's not my project, but a third-party continuation. i don't have any interest in developing for forge 1.16, so that's more or less the "official" port. you'll have to ask them about features
