### ISSUE TITLE
Crash on client side

### ISSUE THREAD

**Issue by masmc05** [phantamanta44/Lazy-AE2#49]
I play stoneblock 2 with my friend, for easier play i made the server apart, and i didn't like the mid-end game AE2 and added your mod, when i made Mass Assembly Chamber i've got some [crashes catched by vanillafix](https://drive.google.com/drive/folders/17M3iN3DbqGHmYSuV6sYyDj45__071nPo?usp=sharing) , there aren't any errors on server side, only on client side, and i can't open the GUI corectly, there is 0 pages when i placed 64 pattern providers 
![image](https://user-images.githubusercontent.com/63639746/110219477-21c43d80-7ec8-11eb-8b99-ec3b062af16a.png), i put a pattern using IO port and it's working, i realy liked your mod so it's a pitty that there is such errors

**Comment by phantamanta44** [comment]
is it possible that the client and server configs aren't synced? it seems like the client thinks the job queue is larger than it actually is, or something like that

**Comment by masmc05** [comment]
i remember i changed one from 64 to 100, but now both are the same (i don't remember switching back), i restarted the game and it's working,can you add a config sync in future?

**Comment by phantamanta44** [comment]
i thought forge automatically synced configs or something like that, but maybe i was mistaken
