### ISSUE TITLE
ME Level Maintainer breaks

### ISSUE THREAD

**Issue by Boyownik** [phantamanta44/Lazy-AE2#5]
Me Level Maintainer keeps breaking when u place it next to fluix cable which is connected to system (has free channels). When You place Maintainer first, and then connect it by fluix cables it wont break. 
Happens on FTB Sky Odyssey (i've added this mod by myself)

**Comment by phantamanta44** [comment]
what do you mean by "breaks"? i just tested this with only AE2 + Lazy-AE2 and it worked fine

could i also get details on your ME system setup?

**Comment by Boyownik** [comment]
By breaks i mean it drops like, player would break it with pickaxe or smth. My system is simple, just few me controllers, smart fluix cables, few interfaces and terminals.
https://giphy.com/gifs/Yobe3alEc2KQXs96Xx

**Comment by phantamanta44** [comment]
do you have a security terminal? i've never seen this behaviour before

**Comment by Boyownik** [comment]
Yeah, i have it, i forgot to mention. I used it to link wireless terminal.

**Comment by phantamanta44** [comment]
should be fixed in 1.1.1: https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/2743864
