### ISSUE TITLE
Recipe oredict problem

### ISSUE THREAD

**Issue by abel1502** [phantamanta44/Lazy-AE2#50]
Aggregator doesn't accept Railcraft's ender dust as a substitute for ae2's one. I'm using the latest versions of both.

**Comment by phantamanta44** [comment]
i'm just using the standard `dustEnderPearl` oredict key, so there shouldn't be a problem on my end (although it seems like it should be fixed on their end, as implied by [this issue](https://github.com/Railcraft/Railcraft/issues/1609))

**Comment by abel1502** [comment]
Indeed, that seems to be the case. I'll use crafttweaker then, as it is suggested there, I guess
