### ISSUE TITLE
Add ''craft from storage'' checkbox to level maintainer

### ISSUE THREAD

**Issue by Rubijox** [phantamanta44/Lazy-AE2#52]
Right now the level maintainer seems to craft then entire recipe tree of what you are trying to maintain from scratch, even when you have most of the materials on hand, which is a total waste of resources...
Why would i want to craft a batch of 64 circuits when i already have 10000 in storage... it adds processing time to something that should be fairly quick and wastes tons of materials

An option to toggle this behavior on and off would be most welcome

**Comment by phantamanta44** [comment]
the level maintainer uses exactly the same autocrafting request mechanism that manually requesting stuff does. maybe check to ensure that the circuits are visible to the crafting cpus?

**Comment by Rubijox** [comment]
that's odd, right now it is no longer doing it
But the circuits were certainly visible, i had a terminal connected on the same me cable as the maintainer and the circuits were clearly visible...
maybe just a fluke? i hope so...

**Comment by phantamanta44** [comment]
seems like it was just a fluke...
