### ISSUE TITLE
(invalid) CraftTweaker: Aggregator not consuming top and bottom input

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/Lazy-AE2#54]
Making custom Aggregator recipe works fine, but top and bottom items not consumed.

My `.zs` code:
```zs
mods.threng.Aggregator.removeRecipe(<threng:material:1>);
mods.threng.Aggregator.addRecipe(<threng:material:1>, <ore:dustFluix>, <ore:dustQuartzBlack>, <ore:ingotSilicon>);
```

Result:
![](https://i.imgur.com/W30CJ27.gif)

How to mark ingredients to be consumed?

**Comment by phantamanta44** [comment]
uh your gif is of the vanilla ae2 inscriber?

**Comment by Krutoy242** [comment]
> uh your gif is of the vanilla ae2 inscriber?

Yes, vanilla Inscriber.

**Comment by Krutoy242** [comment]
How stupid I was!

This is not an Aggregator, this is not the recipe specified in the script, and this is my own mistake in the native AE2 CT code (i implicidly add `true` on `not consume ingredients`). What was I just thinking when making this issue ...

Sorry for invalid issue report.
