### ISSUE TITLE
Can't craft a Calculation Processor in the ME Circuit Etcher, Recipe isn't correct in JEI. 

### ISSUE THREAD

**Issue by tabbeddev** [phantamanta44/Lazy-AE2#56]
Hi.

I'm trying to craft a Calculation Processor in the ME Circuit Etcher, but their is missing a Item in the JEI Recipe and so isn't craftable.

I'm playing the Modpack: Skyfactory 4 [(link to curseforge)](https://www.curseforge.com/minecraft/modpacks/skyfactory-4)
With the required Mods. The AE 2 Channel are disabled.

The JEI-Page is looking like this:
![image](https://user-images.githubusercontent.com/83753407/188480712-837d6d9b-ef81-4cf8-bb42-eda63894eb24.png)

**Comment by phantamanta44** [comment]
Probably the SF4 authors made some oredict change that broke the recipe. I would suggest using crafttweaker to replace the default one with your own working recipe.

**Comment by tabbeddev** [comment]
> Probably the SF4 authors made some oredict change that broke the recipe. I would suggest using crafttweaker to replace the default one with your own working recipe.

Um, how do i do it?

**Comment by zeng-github01** [comment]
> > Probably the SF4 authors made some oredict change that broke the recipe. I would suggest using crafttweaker to replace the default one with your own working recipe.
> 
> Um, how do i do it?

Do you still need to fix this? I have written the corresponding patch on my computer. If there is still need. You can reply to me

**Comment by tabbeddev** [comment]
Hi. Currently i don't need a fix. But you can post it for other users who have the same problem.

**Comment by zeng-github01** [comment]
> Hi. Currently i don't need a fix. But you can post it for other users who have the same problem.

I see

**Comment by zeng-github01** [comment]
About Patch

Put it to {SF4RootPath}\scripts\crafttweaker\modIntegrations   [lazyae2.txt](https://github.com/phantamanta44/Lazy-AE2/files/12709188/lazyae2.txt)


Put it to {SF4RootPath}\scripts\crafttweaker\recipes\mods [lazyae2.txt](https://github.com/phantamanta44/Lazy-AE2/files/12709194/lazyae2.txt)

 and rename file extension to .zs

Find postInit.zs in the CrT directory.
Add after line 68: scripts.crafttweaker.recipes.mods.lazyae2.init();
Add after line 117: scripts.crafttweaker.modIntegrations.lazyae2.init();

The text added is relative to the directory of the file.

**Comment by tabbeddev** [comment]
Alright. I think i can close this Issue now.

**Comment by tabbeddev** [comment]
And thank you zeng-github01!

**Comment by zeng-github01** [comment]
> Alright. I think i can close this Issue now.

In fact, there are a few lines of code on my local patch to delete redundant lazyae2 recipes in SF4, such as the recipe of the charger.
They are in other scripts.  These scripts also fix Extra Cells bugs.  By replacing it with AE additions.  However, these two lines of code are not easy to express.

However, this doesn't affect anything, so be it
