### ISSUE TITLE
Game crashes after placing down mass assembler controller.

### ISSUE THREAD

**Issue by lokep001** [phantamanta44/Lazy-AE2#57]
Everytime I try to launch into the world, I get this error code.

https://mclo.gs/0k66eLi

**Comment by phantamanta44** [comment]
seems like your game just ran out of memory?

**Comment by lokep001** [comment]
Hi sorry that I didn't put enough information. I allocated 8gb to the pack, and it works flawlessly apart from crashing on placing the controller block anywhere on any world. When that happens I cannot launch into the world anymore and it crashes upon placing it.

**Comment by phantamanta44** [comment]
did you set your job queue size to something extremely high?

**Comment by lokep001** [comment]
No its not connected to anything - just placing down the block anywhere crashes the game and then the world is unloadable

**Comment by lokep001** [comment]
Sorry - just reinstalled the mod - must have been something in the config. It's all back to normal now.
