### ISSUE TITLE
Machines wont drop contents when broken

### ISSUE THREAD

**Issue by Sonic2423** [phantamanta44/Lazy-AE2#7]
again tested on my test server. this is not a new problem with libnine 1.1.4 it was already there with 1.1.3. i just remembered that now. when i was looking for the lag cause on my server i realised that my acceleration cards were missing. they also wont drop the recipe materials and nothing is stored in NBT. tried with pickaxe and wrench (wrench will only rotate and sneak right klick doesnt do anything).

**Comment by phantamanta44** [comment]
implemented in https://github.com/phantamanta44/Lazy-AE2/commit/e01d27a21f232e3ef7ef05d93b146f43b47e4577 and https://github.com/phantamanta44/Lazy-AE2/commit/ce0c697af153dd25c8a58063ff85f7d6fecb2723.

**Comment by phantamanta44** [comment]
now live in 1.1.2: https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/2788612
