### ISSUE TITLE
Not using channels.

### ISSUE THREAD

**Issue by Powertx** [phantamanta44/Lazy-AE2#9]
Not sure if this is a bug or intended that way, but the Level Maintainer is not using channels. Not sure about the other blocks. 
In my opinion they should be using a channel.

**Comment by phantamanta44** [comment]
definitely a bug. i'll take a look later

**Comment by phantamanta44** [comment]
brief update: progwml6's maven server is currently down, so i'm unable to make any fix to this issue for now

**Comment by phantamanta44** [comment]
implemented in 1.1.3: https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/2847210
